Repository nettsi/hadouken, pull requests merged in 2021-11, with the labels that each got.

#88 Bugfix/coverage compile options
  cmake/modules/wrappers/detail/coverage_set_variables.cmake
Labels: bug

#90 Dealing with cmake bugs
  cmake/modules/core/BuildVariant.cmake
  cmake/modules/core/DiagnosticFlags_Clang.cmake
  cmake/modules/core/DiagnosticFlags_GCC.cmake
Labels: bug

#91 Small correction
  cmake/modules/core/BuildVariant.cmake
Labels: bug

#92 make_target: added ADD_TEST_PARAMETERS and GTEST_DISCOVER_PARAMETERS …
  README.md
  cmake/modules/core/MakeTarget.cmake
Labels: enhancement

#93 Hadouken is now less verbose.
  cmake/modules/core/BuildVariant.cmake
  cmake/modules/core/FetchConanPackage.cmake
  cmake/modules/toolconf/Doxygen.cmake
  cmake/modules/toolconf/GoogleBenchmark.cmake
  cmake/modules/toolconf/GoogleTest.cmake
  cmake/modules/toolconf/detail/helper_functions.cmake
  cmake/modules/wrappers/Git.cmake
  hadouken.cmake
Labels: enhancement

#94 Coverage feature improvements and maintenance stuff:
  cmake/modules/core/BuildVariant.cmake
  cmake/modules/core/DiagnosticFlags_Clang.cmake
  cmake/modules/core/DiagnosticFlags_GCC.cmake
  cmake/modules/core/FetchConanPackage.cmake
  cmake/modules/core/HardwareConcurrency.cmake
  cmake/modules/core/MakeCompilationUnit.cmake
  cmake/modules/core/MakeComponent.cmake
  cmake/modules/core/MakeProject.cmake
  cmake/modules/core/MakeTarget.cmake
  cmake/modules/core/ProjectMetadataExposure.cmake
  cmake/modules/core/TargetProperties.cmake
  cmake/modules/core/TargetUtilities.cmake
  cmake/modules/core/detail/helper_functions.cmake
  cmake/modules/misc/Log.cmake
  cmake/modules/misc/Utility.cmake
  cmake/modules/toolconf/CCache.cmake
  cmake/modules/toolconf/ClangFormat.cmake
  cmake/modules/toolconf/ClangTidy.cmake
  cmake/modules/toolconf/CppCheck.cmake
  cmake/modules/toolconf/Doxygen.cmake
  cmake/modules/toolconf/GCov.cmake
  cmake/modules/toolconf/GCovR.cmake
  cmake/modules/toolconf/GoogleBenchmark.cmake
  cmake/modules/toolconf/GoogleTest.cmake
  cmake/modules/toolconf/IncludeWhatYouUse.cmake
  cmake/modules/toolconf/LCov.cmake
  cmake/modules/toolconf/LLVMCov.cmake
  cmake/modules/toolconf/LinkWhatYouUse.cmake
  cmake/modules/toolconf/detail/helper_functions.cmake
  cmake/modules/wrappers/Gcovr.cmake
  cmake/modules/wrappers/Lcov.cmake
  cmake/modules/wrappers/detail/coverage_set_variables.cmake
  hadouken.cmake
Labels: bug, enhancement
